env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
overrides: [ ]
settings:
  react:
    version: detect
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  require-jsdoc: 0,
  indent: [ "error", 4 ],
  react/prop-types: 0
}
